version: '3.8'

services:
  bot:
    build: .
    container_name: video-indexing-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./database.sqlite:/app/database.sqlite
    restart: unless-stopped